CREATE TYPE "InviteStatus" AS ENUM ('pending','accepted','expired','revoked');
CREATE TABLE "AuditLog" ("id" TEXT PRIMARY KEY, "tenantId" TEXT, "actorId" TEXT, "action" TEXT NOT NULL, "entityType" TEXT NOT NULL, "entityId" TEXT, "metadata" JSONB, "ipAddress" TEXT, "userAgent" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "FileAttachment" ("id" TEXT PRIMARY KEY, "tenantId" TEXT NOT NULL, "uploadedById" TEXT, "entityType" TEXT NOT NULL, "entityId" TEXT NOT NULL, "fileName" TEXT NOT NULL, "mimeType" TEXT NOT NULL, "sizeBytes" BIGINT NOT NULL, "storageKey" TEXT NOT NULL, "url" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Invite" ("id" TEXT PRIMARY KEY, "tenantId" TEXT NOT NULL, "unitId" TEXT, "invitedById" TEXT, "email" TEXT, "phone" TEXT, "role" "UserRole" NOT NULL DEFAULT 'resident', "tokenHash" TEXT NOT NULL, "status" "InviteStatus" NOT NULL DEFAULT 'pending', "expiresAt" TIMESTAMP(3) NOT NULL, "acceptedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "PasswordResetAttempt" ("id" TEXT PRIMARY KEY, "tenantId" TEXT, "userId" TEXT, "email" TEXT NOT NULL, "codeHash" TEXT, "ipAddress" TEXT, "userAgent" TEXT, "successful" BOOLEAN NOT NULL DEFAULT false, "expiresAt" TIMESTAMP(3), "verifiedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX "AuditLog_tenantId_createdAt_idx" ON "AuditLog"("tenantId","createdAt");
CREATE INDEX "AuditLog_actorId_createdAt_idx" ON "AuditLog"("actorId","createdAt");
CREATE INDEX "AuditLog_entityType_entityId_idx" ON "AuditLog"("entityType","entityId");
CREATE UNIQUE INDEX "FileAttachment_storageKey_key" ON "FileAttachment"("storageKey");
CREATE INDEX "FileAttachment_tenantId_entityType_entityId_idx" ON "FileAttachment"("tenantId","entityType","entityId");
CREATE INDEX "FileAttachment_uploadedById_idx" ON "FileAttachment"("uploadedById");
CREATE UNIQUE INDEX "Invite_tokenHash_key" ON "Invite"("tokenHash");
CREATE INDEX "Invite_tenantId_status_expiresAt_idx" ON "Invite"("tenantId","status","expiresAt");
CREATE INDEX "Invite_unitId_idx" ON "Invite"("unitId");
CREATE INDEX "Invite_email_idx" ON "Invite"("email");
CREATE INDEX "Invite_phone_idx" ON "Invite"("phone");
CREATE INDEX "PasswordResetAttempt_email_createdAt_idx" ON "PasswordResetAttempt"("email","createdAt");
CREATE INDEX "PasswordResetAttempt_userId_createdAt_idx" ON "PasswordResetAttempt"("userId","createdAt");
CREATE INDEX "PasswordResetAttempt_tenantId_createdAt_idx" ON "PasswordResetAttempt"("tenantId","createdAt");
ALTER TABLE "AuditLog" ADD FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE SET NULL;
ALTER TABLE "AuditLog" ADD FOREIGN KEY ("actorId") REFERENCES "User"("id") ON DELETE SET NULL;
ALTER TABLE "FileAttachment" ADD FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE;
ALTER TABLE "FileAttachment" ADD FOREIGN KEY ("uploadedById") REFERENCES "User"("id") ON DELETE SET NULL;
ALTER TABLE "Invite" ADD FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE;
ALTER TABLE "Invite" ADD FOREIGN KEY ("unitId") REFERENCES "Unit"("id") ON DELETE SET NULL;
ALTER TABLE "Invite" ADD FOREIGN KEY ("invitedById") REFERENCES "User"("id") ON DELETE SET NULL;
ALTER TABLE "PasswordResetAttempt" ADD FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE SET NULL;
ALTER TABLE "PasswordResetAttempt" ADD FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL;
