ALTER TABLE "Entrance" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "Floor" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "InvoiceLine" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "PaymentAllocation" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "MeterReading" ADD COLUMN "tenantId" TEXT;
ALTER TABLE "WorkOrder" ADD COLUMN "tenantId" TEXT;
UPDATE "Entrance" e SET "tenantId" = b."tenantId" FROM "Building" b WHERE e."buildingId" = b."id";
UPDATE "Floor" f SET "tenantId" = e."tenantId" FROM "Entrance" e WHERE f."entranceId" = e."id";
UPDATE "InvoiceLine" l SET "tenantId" = i."tenantId" FROM "Invoice" i WHERE l."invoiceId" = i."id";
UPDATE "PaymentAllocation" a SET "tenantId" = p."tenantId" FROM "Payment" p WHERE a."paymentId" = p."id";
UPDATE "MeterReading" r SET "tenantId" = m."tenantId" FROM "Meter" m WHERE r."meterId" = m."id";
UPDATE "WorkOrder" w SET "tenantId" = r."tenantId" FROM "MaintenanceRequest" r WHERE w."maintenanceRequestId" = r."id";
ALTER TABLE "Entrance" ALTER COLUMN "tenantId" SET NOT NULL;
ALTER TABLE "Floor" ALTER COLUMN "tenantId" SET NOT NULL;
ALTER TABLE "InvoiceLine" ALTER COLUMN "tenantId" SET NOT NULL;
ALTER TABLE "PaymentAllocation" ALTER COLUMN "tenantId" SET NOT NULL;
ALTER TABLE "MeterReading" ALTER COLUMN "tenantId" SET NOT NULL;
ALTER TABLE "WorkOrder" ALTER COLUMN "tenantId" SET NOT NULL;
ALTER TABLE "Notification" ALTER COLUMN "tenantId" SET NOT NULL;
ALTER TABLE "AuditLog" ALTER COLUMN "tenantId" SET NOT NULL;
ALTER TABLE "PasswordResetAttempt" ALTER COLUMN "tenantId" SET NOT NULL;
ALTER TABLE "AuditLog" DROP CONSTRAINT "AuditLog_tenantId_fkey";
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PasswordResetAttempt" DROP CONSTRAINT "PasswordResetAttempt_tenantId_fkey";
ALTER TABLE "PasswordResetAttempt" ADD CONSTRAINT "PasswordResetAttempt_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE INDEX "Entrance_tenantId_idx" ON "Entrance"("tenantId");
CREATE INDEX "Floor_tenantId_idx" ON "Floor"("tenantId");
CREATE INDEX "InvoiceLine_tenantId_idx" ON "InvoiceLine"("tenantId");
CREATE INDEX "PaymentAllocation_tenantId_idx" ON "PaymentAllocation"("tenantId");
CREATE INDEX "MeterReading_tenantId_readAt_idx" ON "MeterReading"("tenantId","readAt");
CREATE INDEX "WorkOrder_tenantId_status_idx" ON "WorkOrder"("tenantId","status");
ALTER TABLE "Entrance" ADD CONSTRAINT "Entrance_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Floor" ADD CONSTRAINT "Floor_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "InvoiceLine" ADD CONSTRAINT "InvoiceLine_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PaymentAllocation" ADD CONSTRAINT "PaymentAllocation_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "MeterReading" ADD CONSTRAINT "MeterReading_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "WorkOrder" ADD CONSTRAINT "WorkOrder_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "Tenant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
